// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvxjjchztpufzasfdyzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eGpqY2h6dHB1Znphc2ZkeXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzAzNDQsImV4cCI6MjA2MDkwNjM0NH0.nu-nDUHJrmA6H8ztyRzRhjSHAA_p-YRnwMoWSb-B_fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);